### PR TITLE
Capture log output in "exiting the process" test

### PR DESCRIPTION
**Pull request by axelson**

### CODE REVIEW

**Comment by fhunleth** [comment]
Ahh... It looks like the failures are due to needing to run `mix format`. 

Super-thanks for working on this! I'm really glad to see `muontrap` getting some attention.

**Comment by axelson** [comment]
Ah, ok. Not sure why my formatter locally isn't picking that up so I added a change the `.formatter.exs` too. Should pass now.

**Comment by fhunleth** [comment]
It passed! Thanks again.

**Comment by axelson** [comment]
Thanks for making muontrap! It fulfills an important need (and now that these are merged I will try and actually use it 😂on a project)

**Pull request merged**
